// The README itself. GitHub keeps a small set of HTML and drops all styling, so the display type lives
// in the pictures and everything a reader might select, search or have read aloud stays text.
import { esc } from './svg.js';

export const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
export const cardFile = (work) => `work-${slug(work.name)}.svg`;

const img = (file, width, alt) => `<img src="readme/img/${file}" width="${width}" alt="${esc(alt)}">`;
const link = (url, inner) => (url ? `<a href="${esc(url)}">${inner}</a>` : inner);
const center = (inner) => `<p align="center">${inner}</p>`;
// +4553737514 → +45 53 73 75 14; anything else as the page writes it.
const phone = (p) => (/^\+45\d{8}$/.test(p) ? `+45 ${p.slice(3).match(/../g).join(' ')}` : p);

function section(heading, file) {
  const title = center(img(file, 520, heading.title));
  return heading.note ? `${title}\n${center(`<i>${esc(heading.note)}</i>`)}` : title;
}

const works = (list) =>
  center(`\n${list.map((w) => link(w.url, img(cardFile(w), 400, `No. ${w.no}, ${w.name}. ${w.kind}. ${w.line}`))).join('\n')}\n`);

const group = (g) =>
  center(`<b>${esc(g.name)}</b><br>\n${g.items.map((i) => `${link(i.url, `<b>${esc(i.name)}</b>`)} · ${esc(i.line)}`).join('<br>\n')}`);

export function renderReadme(m) {
  const { intro, headings: h, about, contact: c } = m;
  return [
    '<!-- Generated by `npm run readme` from templates/partials/ and readme/copy.en.json. Edit those, not this file. -->',
    center(link('https://cocode.dk', img('hero.svg', '100%', `${intro.kicker}. ${intro.title.join(' ')}`))),
    center(esc(intro.lead)),
    '<br>',
    section(h.works, 'heading-works.svg'),
    works(m.works),
    '<br>',
    section(h.catalogue, 'heading-catalogue.svg'),
    ...m.groups.map(group),
    '<br>',
    section(h.services, 'heading-services.svg'),
    ...m.services.map((s) => center(`<b>${esc(s.name)}</b><br>\n${esc(s.line)}`)),
    '<br>',
    section(h.about, 'heading-about.svg'),
    ...about.paragraphs.map((p) => center(esc(p))),
    center(`<i>${esc(about.signature)}</i><br>\n<sub>${esc(about.notes)}</sub>`),
    '<br>',
    center(link(`mailto:${c.email}`, img('contact.svg', 400, `${c.heading}. ${c.lead} ${c.email}`))),
    center(`<a href="https://cocode.dk">cocode.dk</a> · <a href="${esc(c.linkedin)}">LinkedIn</a> · ${esc(phone(c.phone))}`),
    '',
  ].join('\n\n');
}
